services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: "3.10"


